// Day 2 of the NIS2 5-day gap assessment.
// Edit this file (not data/gap-assessment.json) and run
// `bun run build:json` to regenerate the published JSON artefact.

import type { GapQuestion } from "../schema";
import { CRITICALITY, RESPONDENT, CONSEQUENCE, TIME_TO_FIX } from "../schema";

export const day2Questions: GapQuestion[] = [
  {
    id: "gap-2-01",
    domain: 2,
    text: {
      en: "Does your organization have a documented risk assessment methodology?",
      de: "Verfügt Ihre Organisation über eine dokumentierte Risikobewertungsmethodik?",
    },
    plainText: {
      en: "Is there a written process for how you identify and evaluate security risks? (Even a simple spreadsheet process counts.)",
      de: "Gibt es einen schriftlich festgelegten Prozess, wie Sie Sicherheitsrisiken identifizieren und bewerten? (Auch ein einfacher Tabellenkalkulationsprozess zählt.)",
    },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.FINE,
    fineExposure: true,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 2,
    dependsOn: [],
  },
  {
    id: "gap-2-02",
    domain: 2,
    text: {
      en: "Does the methodology cover likelihood and impact assessment?",
      de: "Deckt die Methodik die Bewertung von Eintrittswahrscheinlichkeit und Auswirkung ab?",
    },
    plainText: {
      en: "When you find a risk, do you assess both \"how likely is this?\" and \"how bad would it be?\"",
      de: "Wenn Sie ein Risiko finden, bewerten Sie dann sowohl \"Wie wahrscheinlich ist das?\" als auch \"Wie schlimm wäre es?\"",
    },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 2,
    dependsOn: ["gap-2-01"],
  },
  {
    id: "gap-2-03",
    domain: 2,
    text: {
      en: "Does the methodology consider more than just cyber attacks?",
      de: "Berücksichtigt die Methodik mehr als nur Cyberangriffe?",
    },
    plainText: {
      en: "Do you also consider power outages, floods, employee mistakes, supplier failures -- not just hackers?",
      de: "Berücksichtigen Sie auch Stromausfälle, Überschwemmungen, Mitarbeiterfehler, Lieferantenausfälle -- nicht nur Hacker?",
    },
    legalBasis: "Art 21(1)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 2,
    dependsOn: ["gap-2-01"],
  },
  {
    id: "gap-2-04",
    domain: 2,
    text: {
      en: "Is the methodology proportionate to your organization's size and risk exposure?",
      de: "Ist die Methodik verhältnismäßig zur Größe und Risikoexposition Ihrer Organisation?",
    },
    plainText: {
      en: "Is your approach right-sized for your company? A 50-person company doesn't need the same process as a bank.",
      de: "Ist Ihr Ansatz auf Ihr Unternehmen zugeschnitten? Ein 50-Personen-Unternehmen braucht nicht denselben Prozess wie eine Bank.",
    },
    legalBasis: "Art 21(1)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 2,
    dependsOn: ["gap-2-01"],
  },
  {
    id: "gap-2-05",
    domain: 2,
    text: {
      en: "Do you maintain a list of all your IT systems, software, and equipment?",
      de: "Führen Sie eine Liste aller Ihrer IT-Systeme, Software und Geräte?",
    },
    plainText: {
      en: "Do you know every server, laptop, application, and piece of network equipment your company uses? Written down somewhere?",
      de: "Kennen Sie jeden Server, Laptop, jede Anwendung und jedes Netzwerkgerät, das Ihr Unternehmen nutzt? Irgendwo aufgeschrieben?",
    },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.FINE,
    fineExposure: true,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 2,
    dependsOn: [],
  },
  {
    id: "gap-2-06",
    domain: 2,
    text: {
      en: "Are assets classified by how critical they are to your business?",
      de: "Sind die Assets nach ihrer Kritikalität für Ihr Unternehmen klassifiziert?",
    },
    plainText: {
      en: "Do you know which systems would hurt most if they went down?",
      de: "Wissen Sie, welche Systeme den größten Schaden verursachen würden, wenn sie ausfallen?",
    },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 2,
    dependsOn: ["gap-2-05"],
  },
  {
    id: "gap-2-07",
    domain: 2,
    text: {
      en: "Does the inventory distinguish between office IT and operational technology (OT)?",
      de: "Unterscheidet das Inventar zwischen Büro-IT und Betriebstechnologie (OT)?",
    },
    plainText: {
      en: "If you have industrial equipment, production lines, or building management systems, are they listed separately from office computers?",
      de: "Wenn Sie Industrieanlagen, Produktionslinien oder Gebäudemanagementsysteme haben, sind diese getrennt von Bürocomputern aufgelistet?",
    },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 2,
    dependsOn: ["gap-2-05"],
  },
  {
    id: "gap-2-08",
    domain: 2,
    text: {
      en: "Is the asset inventory reviewed and updated at least annually?",
      de: "Wird das Asset-Inventar mindestens jährlich überprüft und aktualisiert?",
    },
    plainText: { en: "When was the list last updated?", de: "Wann wurde die Liste zuletzt aktualisiert?" },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 2,
    dependsOn: ["gap-2-05"],
  },
  {
    id: "gap-2-09",
    domain: 2,
    text: {
      en: "Have you conducted a cybersecurity risk assessment within the past 12 months?",
      de: "Haben Sie in den letzten 12 Monaten eine Cybersicherheits-Risikobewertung durchgeführt?",
    },
    plainText: {
      en: "Have you actually sat down and identified what could go wrong, in the last year?",
      de: "Haben Sie sich im letzten Jahr tatsächlich hingesetzt und ermittelt, was schiefgehen könnte?",
    },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.FINE,
    fineExposure: true,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 2,
    dependsOn: ["gap-2-01", "gap-2-05"],
  },
  {
    id: "gap-2-10",
    domain: 2,
    text: {
      en: "Does the risk assessment cover all assets in the inventory?",
      de: "Deckt die Risikobewertung alle Assets im Inventar ab?",
    },
    plainText: {
      en: "Did you assess risks for everything on your asset list, not just the obvious ones?",
      de: "Haben Sie Risiken für alles auf Ihrer Asset-Liste bewertet, nicht nur für die offensichtlichen?",
    },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 2,
    dependsOn: ["gap-2-09", "gap-2-05"],
  },
  {
    id: "gap-2-11",
    domain: 2,
    text: {
      en: "Are identified risks documented with an owner, likelihood, impact, and treatment plan?",
      de: "Sind identifizierte Risiken mit einem Verantwortlichen, Eintrittswahrscheinlichkeit, Auswirkung und Behandlungsplan dokumentiert?",
    },
    plainText: {
      en: "For each risk you found, is it written down who's responsible, how likely it is, how bad it would be, and what you're doing about it?",
      de: "Ist für jedes gefundene Risiko festgehalten, wer verantwortlich ist, wie wahrscheinlich es ist, wie schlimm es wäre und was Sie dagegen tun?",
    },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 2,
    dependsOn: ["gap-2-09"],
  },
  {
    id: "gap-2-12",
    domain: 2,
    text: {
      en: "Are risk acceptance decisions formally approved by management in writing?",
      de: "Werden Risikoakzeptanzentscheidungen von der Geschäftsleitung formell schriftlich genehmigt?",
    },
    plainText: {
      en: "If you decided to accept a risk (do nothing about it), did the CEO sign off on that decision?",
      de: "Wenn Sie sich entschieden haben, ein Risiko zu akzeptieren (nichts dagegen zu tun), hat der CEO diese Entscheidung schriftlich genehmigt?",
    },
    legalBasis: "Art 20(1)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.CEO,
    consequence: CONSEQUENCE.PERSONAL_LIABILITY,
    fineExposure: true,
    timeToFix: TIME_TO_FIX.QUICK_WIN,
    day: 2,
    dependsOn: ["gap-2-09"],
  },
  {
    id: "gap-2-13",
    domain: 2,
    text: {
      en: "Is the risk assessment reviewed after significant changes or after security incidents?",
      de: "Wird die Risikobewertung nach wesentlichen Änderungen oder nach Sicherheitsvorfällen überprüft?",
    },
    plainText: {
      en: "When something big changes (new system, new office, security incident), do you re-assess?",
      de: "Wenn sich etwas Wesentliches ändert (neues System, neues Büro, Sicherheitsvorfall), führen Sie dann eine Neubewertung durch?",
    },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 2,
    dependsOn: ["gap-2-09"],
  },
  {
    id: "gap-2-14",
    domain: 2,
    text: {
      en: "Does your organization have a formal information security policy signed by management?",
      de: "Verfügt Ihre Organisation über eine formelle Informationssicherheitsrichtlinie, die von der Geschäftsleitung unterzeichnet ist?",
    },
    plainText: {
      en: "Is there a written document that says \"this is how we do security,\" signed by the CEO?",
      de: "Gibt es ein schriftliches Dokument, das besagt \"So handhaben wir Sicherheit\", unterzeichnet vom CEO?",
    },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.CEO,
    consequence: CONSEQUENCE.FINE,
    fineExposure: true,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 2,
    dependsOn: [],
  },
  {
    id: "gap-2-15",
    domain: 2,
    text: {
      en: "Does the policy cover all 10 NIS2 security measures?",
      de: "Deckt die Richtlinie alle 10 NIS2-Sicherheitsmaßnahmen ab?",
    },
    plainText: {
      en: "Does your security policy address: risk management, incidents, business continuity, supply chain, secure systems, effectiveness testing, training, cryptography, access control, and secure communications?",
      de: "Behandelt Ihre Sicherheitsrichtlinie: Risikomanagement, Vorfälle, Betriebskontinuität, Lieferkette, sichere Systeme, Wirksamkeitsprüfung, Schulungen, Kryptografie, Zugangskontrolle und sichere Kommunikation?",
    },
    legalBasis: "Art 21(2)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.FINE,
    fineExposure: true,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 2,
    dependsOn: ["gap-2-14"],
  },
  {
    id: "gap-2-16",
    domain: 2,
    text: {
      en: "Is the policy reviewed and updated at least annually?",
      de: "Wird die Richtlinie mindestens jährlich überprüft und aktualisiert?",
    },
    plainText: { en: "When was it last reviewed?", de: "Wann wurde sie zuletzt überprüft?" },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 2,
    dependsOn: ["gap-2-14"],
  },
  {
    id: "gap-2-17",
    domain: 2,
    text: {
      en: "Is the policy communicated to all employees?",
      de: "Ist die Richtlinie allen Mitarbeitern bekannt gemacht?",
    },
    plainText: {
      en: "Does every employee know the policy exists and where to find it?",
      de: "Weiß jeder Mitarbeiter, dass die Richtlinie existiert und wo sie zu finden ist?",
    },
    legalBasis: "Art 21(2)(a)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.HR,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.QUICK_WIN,
    day: 2,
    dependsOn: ["gap-2-14"],
  },
];
