// Day 5 of the NIS2 5-day gap assessment.
// Edit this file (not data/gap-assessment.json) and run
// `bun run build:json` to regenerate the published JSON artefact.

import type { GapQuestion } from "../schema";
import { CRITICALITY, RESPONDENT, CONSEQUENCE, TIME_TO_FIX } from "../schema";

export const day5Questions: GapQuestion[] = [
  {
    id: "gap-6-01",
    domain: 6,
    text: {
      en: "Do you have a policy for secure acquisition of IT systems and services?",
      de: "Haben Sie eine Richtlinie für die sichere Beschaffung von IT-Systemen und -Diensten?",
    },
    plainText: {
      en: "When you buy new software or hardware, do you check if it's secure? Or do you just pick the cheapest option?",
      de: "Wenn Sie neue Software oder Hardware kaufen, prüfen Sie, ob sie sicher ist? Oder wählen Sie einfach die günstigste Option?",
    },
    legalBasis: "Art 21(2)(e)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-6-02",
    domain: 6,
    text: {
      en: "If you develop software, do you follow secure development practices?",
      de: "Wenn Sie Software entwickeln, befolgen Sie sichere Entwicklungspraktiken?",
    },
    plainText: {
      en: "If your company builds software (even internal tools), is security part of the development process?",
      de: "Wenn Ihr Unternehmen Software entwickelt (auch interne Tools), ist Sicherheit Teil des Entwicklungsprozesses?",
    },
    legalBasis: "Art 21(2)(e)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-6-03",
    domain: 6,
    text: {
      en: "Do you have a vulnerability management and patch management process?",
      de: "Haben Sie einen Prozess für Schwachstellen- und Patch-Management?",
    },
    plainText: {
      en: "When security updates come out for your software, do you apply them? Is there a process for it?",
      de: "Wenn Sicherheitsupdates für Ihre Software erscheinen, installieren Sie diese? Gibt es dafür einen Prozess?",
    },
    legalBasis: "Art 21(2)(e)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-6-04",
    domain: 6,
    text: {
      en: "Are critical security patches applied within a defined timeframe?",
      de: "Werden kritische Sicherheitspatches innerhalb eines definierten Zeitrahmens eingespielt?",
    },
    plainText: {
      en: "How quickly do you install urgent security updates? Days? Weeks? Never?",
      de: "Wie schnell installieren Sie dringende Sicherheitsupdates? Tage? Wochen? Nie?",
    },
    legalBasis: "Art 21(2)(e)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 5,
    dependsOn: ["gap-6-03"],
  },
  {
    id: "gap-6-05",
    domain: 6,
    text: {
      en: "Do you perform security testing before deploying new systems or changes?",
      de: "Führen Sie Sicherheitstests durch, bevor Sie neue Systeme oder Änderungen in Betrieb nehmen?",
    },
    plainText: {
      en: "Before putting a new system live, do you check if it's secure?",
      de: "Bevor Sie ein neues System in Betrieb nehmen, prüfen Sie, ob es sicher ist?",
    },
    legalBasis: "Art 21(2)(e)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-7-01",
    domain: 7,
    text: {
      en: "Do you have any way to measure whether your security measures are working?",
      de: "Haben Sie eine Möglichkeit zu messen, ob Ihre Sicherheitsmaßnahmen funktionieren?",
    },
    plainText: {
      en: "Can you answer the question: \"are we more secure this year than last year?\" with evidence?",
      de: "Können Sie die Frage beantworten: \"Sind wir dieses Jahr sicherer als letztes Jahr?\" -- mit Belegen?",
    },
    legalBasis: "Art 21(2)(f)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.FINE,
    fineExposure: true,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-7-02",
    domain: 7,
    text: {
      en: "Do you conduct regular internal reviews of your security measures?",
      de: "Führen Sie regelmäßige interne Überprüfungen Ihrer Sicherheitsmaßnahmen durch?",
    },
    plainText: {
      en: "Does someone periodically check if the security rules are actually being followed?",
      de: "Prüft jemand regelmäßig, ob die Sicherheitsregeln tatsächlich eingehalten werden?",
    },
    legalBasis: "Art 21(2)(f)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-7-03",
    domain: 7,
    text: {
      en: "Are the results of effectiveness assessments reported to management?",
      de: "Werden die Ergebnisse von Wirksamkeitsbewertungen der Geschäftsleitung berichtet?",
    },
    plainText: {
      en: "Does the CEO see the results of security reviews?",
      de: "Sieht der CEO die Ergebnisse der Sicherheitsüberprüfungen?",
    },
    legalBasis: "Art 20(1)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.CEO,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 5,
    dependsOn: ["gap-7-01"],
  },
  {
    id: "gap-7-04",
    domain: 7,
    text: {
      en: "Do you have a corrective action process for identified deficiencies?",
      de: "Haben Sie einen Korrekturmaßnahmenprozess für festgestellte Mängel?",
    },
    plainText: {
      en: "When you find a security problem, is there a process to track it until it's fixed?",
      de: "Wenn Sie ein Sicherheitsproblem finden, gibt es einen Prozess, um es bis zur Behebung zu verfolgen?",
    },
    legalBasis: "Art 21(2)(f)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-7-05",
    domain: 7,
    text: {
      en: "Have you considered external penetration testing or vulnerability assessments?",
      de: "Haben Sie externe Penetrationstests oder Schwachstellenbewertungen in Betracht gezogen?",
    },
    plainText: {
      en: "Has anyone tried to break into your systems on purpose to see if they could?",
      de: "Hat jemand absichtlich versucht, in Ihre Systeme einzudringen, um zu sehen, ob es möglich ist?",
    },
    legalBasis: "Art 21(2)(f)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-9-01",
    domain: 9,
    text: {
      en: "Do you have a documented cryptography policy?",
      de: "Haben Sie eine dokumentierte Kryptografierichtlinie?",
    },
    plainText: {
      en: "Is there a written policy about how your company uses encryption? (Even a short one counts.)",
      de: "Gibt es eine schriftliche Richtlinie darüber, wie Ihr Unternehmen Verschlüsselung einsetzt? (Auch eine kurze zählt.)",
    },
    legalBasis: "Art 21(2)(h)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-9-02",
    domain: 9,
    text: {
      en: "Is data encrypted in transit (HTTPS for all web services, TLS for email)?",
      de: "Werden Daten bei der Übertragung verschlüsselt (HTTPS für alle Webdienste, TLS für E-Mail)?",
    },
    plainText: {
      en: "When data travels between systems (website, email, file transfers), is it encrypted? Check: does your website show a padlock?",
      de: "Wenn Daten zwischen Systemen übertragen werden (Website, E-Mail, Dateitransfers), sind sie verschlüsselt? Prüfen Sie: Zeigt Ihre Website ein Schloss-Symbol?",
    },
    legalBasis: "Art 21(2)(h)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-9-03",
    domain: 9,
    text: {
      en: "Is data encrypted at rest where appropriate (disk encryption, database encryption)?",
      de: "Werden Daten im Ruhezustand wo angemessen verschlüsselt (Festplattenverschlüsselung, Datenbankverschlüsselung)?",
    },
    plainText: {
      en: "Are your laptops encrypted? (Windows BitLocker, Mac FileVault?) What about server hard drives?",
      de: "Sind Ihre Laptops verschlüsselt? (Windows BitLocker, Mac FileVault?) Was ist mit den Festplatten der Server?",
    },
    legalBasis: "Art 21(2)(h)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-9-04",
    domain: 9,
    text: {
      en: "Do you have a process for managing encryption keys?",
      de: "Haben Sie einen Prozess für das Management von Verschlüsselungsschlüsseln?",
    },
    plainText: {
      en: "If you use encryption, who has the keys? What happens if that person leaves?",
      de: "Wenn Sie Verschlüsselung nutzen, wer hat die Schlüssel? Was passiert, wenn diese Person das Unternehmen verlässt?",
    },
    legalBasis: "Art 21(2)(h)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-11-01",
    domain: 11,
    text: {
      en: "Are internal communications channels secured?",
      de: "Sind interne Kommunikationskanäle gesichert?",
    },
    plainText: {
      en: "Is your company email encrypted? Do you use secure messaging (Teams, Signal) instead of unencrypted SMS for sensitive topics?",
      de: "Ist Ihre Firmen-E-Mail verschlüsselt? Nutzen Sie sichere Messenger (Teams, Signal) statt unverschlüsselter SMS für sensible Themen?",
    },
    legalBasis: "Art 21(2)(j)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-11-02",
    domain: 11,
    text: {
      en: "Are emergency/out-of-band communication channels defined for crisis situations?",
      de: "Sind Notfall-/Out-of-Band-Kommunikationskanäle für Krisensituationen definiert?",
    },
    plainText: {
      en: "If your email goes down during a cyberattack, how does the team communicate? Is there a backup plan (phone tree, Signal group, personal email list)?",
      de: "Wenn Ihre E-Mail während eines Cyberangriffs ausfällt, wie kommuniziert das Team? Gibt es einen Backup-Plan (Telefonkette, Signal-Gruppe, private E-Mail-Liste)?",
    },
    legalBasis: "Art 21(2)(j)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.QUICK_WIN,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-11-03",
    domain: 11,
    text: {
      en: "Is there a policy for secure use of mobile devices?",
      de: "Gibt es eine Richtlinie für die sichere Nutzung mobiler Geräte?",
    },
    plainText: {
      en: "Are company phones and personal phones used for work covered by security rules? (Screen lock, encryption, remote wipe?)",
      de: "Unterliegen Firmenhandys und private Handys, die für die Arbeit genutzt werden, Sicherheitsregeln? (Bildschirmsperre, Verschlüsselung, Fernlöschung?)",
    },
    legalBasis: "Art 21(2)(j)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-12-01",
    domain: 12,
    text: {
      en: "Do you have a firewall protecting your network?",
      de: "Haben Sie eine Firewall, die Ihr Netzwerk schützt?",
    },
    plainText: {
      en: "Is there a firewall between your company network and the internet?",
      de: "Gibt es eine Firewall zwischen Ihrem Unternehmensnetzwerk und dem Internet?",
    },
    legalBasis: "Art 21(2)(e)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-12-02",
    domain: 12,
    text: {
      en: "Is your WiFi network secured and separate from guest access?",
      de: "Ist Ihr WLAN-Netzwerk gesichert und vom Gastzugang getrennt?",
    },
    plainText: {
      en: "Is your company WiFi password-protected? Is the guest WiFi on a separate network from your business systems?",
      de: "Ist Ihr Firmen-WLAN passwortgeschützt? Ist das Gäste-WLAN in einem separaten Netzwerk von Ihren Geschäftssystemen?",
    },
    legalBasis: "Art 21(2)(e)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-12-03",
    domain: 12,
    text: {
      en: "If you have operational technology (OT) or industrial systems, are they on a separate network from office IT?",
      de: "Wenn Sie Betriebstechnologie (OT) oder industrielle Systeme haben, befinden sich diese in einem separaten Netzwerk von der Büro-IT?",
    },
    plainText: {
      en: "Are your production/manufacturing systems on a different network than your office computers and email?",
      de: "Befinden sich Ihre Produktions-/Fertigungssysteme in einem anderen Netzwerk als Ihre Bürocomputer und E-Mail?",
    },
    legalBasis: "Art 21(2)(e)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.MONTHS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-12-04",
    domain: 12,
    text: {
      en: "Do you have intrusion detection or prevention systems?",
      de: "Haben Sie Systeme zur Erkennung oder Verhinderung von Eindringlingen (IDS/IPS)?",
    },
    plainText: {
      en: "Is there anything watching your network for suspicious activity?",
      de: "Gibt es etwas, das Ihr Netzwerk auf verdächtige Aktivitäten überwacht?",
    },
    legalBasis: "Art 21(2)(e)",
    criticality: CRITICALITY.MEDIUM,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.OPERATIONAL_RISK,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.MONTHS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-14-01",
    domain: 14,
    text: {
      en: "Are all security policies signed by management with dates?",
      de: "Sind alle Sicherheitsrichtlinien von der Geschäftsleitung mit Datum unterzeichnet?",
    },
    plainText: {
      en: "Can you show a signed, dated document for each of your security policies?",
      de: "Können Sie für jede Ihrer Sicherheitsrichtlinien ein unterschriebenes, datiertes Dokument vorzeigen?",
    },
    legalBasis: "Art 20(1)",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.CEO,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.QUICK_WIN,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-14-02",
    domain: 14,
    text: {
      en: "Do you maintain an audit trail of security-relevant decisions and changes?",
      de: "Führen Sie eine Audit-Spur über sicherheitsrelevante Entscheidungen und Änderungen?",
    },
    plainText: {
      en: "If the BSI asks \"who decided to accept this risk and when?\", can you show them?",
      de: "Wenn das BSI fragt \"Wer hat entschieden, dieses Risiko zu akzeptieren, und wann?\", können Sie es nachweisen?",
    },
    legalBasis: "§30 BSIG",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.FINE,
    fineExposure: true,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-14-03",
    domain: 14,
    text: {
      en: "Can you produce evidence of your security measures on request?",
      de: "Können Sie auf Anfrage Nachweise Ihrer Sicherheitsmaßnahmen vorlegen?",
    },
    plainText: {
      en: "If an auditor says \"show me your MFA is enabled,\" can you take a screenshot right now?",
      de: "Wenn ein Prüfer sagt \"Zeigen Sie mir, dass Ihre MFA aktiviert ist\", können Sie jetzt sofort einen Screenshot machen?",
    },
    legalBasis: "§39 BSIG",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.FINE,
    fineExposure: true,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-14-04",
    domain: 14,
    text: {
      en: "Are evidence documents timestamped?",
      de: "Sind Nachweisdokumente mit Zeitstempeln versehen?",
    },
    plainText: {
      en: "Do your screenshots and documents have dates on them?",
      de: "Haben Ihre Screenshots und Dokumente ein Datum?",
    },
    legalBasis: "BSI guidance",
    criticality: CRITICALITY.LOW,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.QUICK_WIN,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-14-05",
    domain: 14,
    text: {
      en: "Is there a central location for all compliance documentation?",
      de: "Gibt es einen zentralen Ablageort für alle Compliance-Dokumentation?",
    },
    plainText: {
      en: "Is all your security documentation in one place, or scattered across email, SharePoint, local drives, and someone's head?",
      de: "Ist Ihre gesamte Sicherheitsdokumentation an einem Ort, oder verteilt über E-Mail, SharePoint, lokale Laufwerke und den Kopf von jemandem?",
    },
    legalBasis: "Best practice",
    criticality: CRITICALITY.LOW,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-14-06",
    domain: 14,
    text: {
      en: "Is documentation versioned and change-tracked?",
      de: "Ist die Dokumentation versioniert und werden Änderungen nachverfolgt?",
    },
    plainText: {
      en: "Can you show what changed between version 1 and version 2 of a policy?",
      de: "Können Sie zeigen, was sich zwischen Version 1 und Version 2 einer Richtlinie geändert hat?",
    },
    legalBasis: "Best practice",
    criticality: CRITICALITY.LOW,
    respondent: RESPONDENT.IT,
    consequence: CONSEQUENCE.AUDIT_FINDING,
    fineExposure: false,
    timeToFix: TIME_TO_FIX.DAYS,
    day: 5,
    dependsOn: [],
  },
  {
    id: "gap-14-07",
    domain: 14,
    text: {
      en: "Could you respond to a BSI information request within the timeframe required?",
      de: "Könnten Sie auf eine BSI-Informationsanfrage innerhalb der geforderten Frist antworten?",
    },
    plainText: {
      en: "If the BSI sends you a letter asking for evidence, can you respond quickly -- or would it take weeks to gather everything?",
      de: "Wenn das BSI Ihnen einen Brief mit der Bitte um Nachweise schickt, können Sie schnell antworten -- oder würde es Wochen dauern, alles zusammenzustellen?",
    },
    legalBasis: "§40 BSIG",
    criticality: CRITICALITY.HIGH,
    respondent: RESPONDENT.CEO,
    consequence: CONSEQUENCE.FINE,
    fineExposure: true,
    timeToFix: TIME_TO_FIX.WEEKS,
    day: 5,
    dependsOn: [],
  },
];
